---
title: "001_growth_curves"
author: "Emily Conklin"
date: "2024-12-05"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)

```

```{r growth curves}

#read in input data extracted from spreadsheets
cleaned_input <- read.csv("../inputs/cleandf_params.csv")

#calculate aboveground carbon as a function of tree taxon and age class
chapman_richards <- function(A, k, p, age){
  agc <- A * (1 - exp(-k * age))^p
  return(agc)
}

#calculate growth rate per age class
agc_rate <- function(agc, age){
  rate_out <- agc / age
  return(rate_out)
}

#run examples
# NOTE - it will take an extra step but we can do custom "n" per species in the future
test_group <- "Pseudotsuga"
n_age_classes <- 150 
n_species <- length(unique(cleaned_input$group))

#select relevant columns and add 'p' parameter
growth_params <- cleaned_input %>%
  select(group, A, k) %>%
  mutate(p = 2) # NOTE - double check what p is - expansion of plantation or something else?

#run AGC and rate functions per age class per species
age_classes <- do.call("rbind", replicate(n_age_classes, growth_params, simplify = FALSE)) %>%
  arrange(group) %>%
  mutate(age = rep(seq(from = 1, to = n_age_classes), times = n_species)) %>%
  mutate(agc = chapman_richards(A, k, p, age)) %>%
  mutate(agc_rate = agc_rate(agc, age))

#quick test plot
ggplot(age_classes) +
  geom_line(aes(x = age, y = agc)) +
  facet_wrap(facets = vars(group))

```
